name: state_machine
version: 2.2.11
description: Finite state machine library. Easily define legal state transitions.
    Listen to state entrances, departures, and transitions.
homepage: https://github.com/Workiva/state_machine

environment:
    sdk: ">=2.11.0 <3.0.0"

dependencies:
  w_common: '^2.0.0'

dev_dependencies:
    build_runner: '>=1.6.2 <3.0.0'
    build_web_compilers: ^3.2.7
    dart_style: ^2.1.1
    test: ^1.17.12
