name: state_machine
version: 2.2.9
description: Finite state machine library. Easily define legal state transitions.
    Listen to state entrances, departures, and transitions.
homepage: https://github.com/Workiva/state_machine

environment:
    sdk: ">=2.11.0 <3.0.0"

dependencies:
    w_common: '>=1.21.8 <3.0.0'

dev_dependencies:
    build_runner: ^2.1.2
    build_test: ^2.1.3
    build_web_compilers: ^3.0.0
    dart_dev: ^3.8.7
    dart_style: ^2.1.1
    test: ^1.17.12
