name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  pull-requests: write
  contents: write
  id-token: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.13.4, 2.18.7 ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --set-exit-if-changed .
        if: ${{ matrix.sdk == '2.18.7' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
      - uses: anchore/sbom-action@v0
        if: ${{ matrix.sdk == '2.18.7' }}
        with:
          path: ./
          format: cyclonedx-json
